### ISSUE TITLE
Cannot use SerialBluetooth with ESP32-S3

### ISSUE THREAD

**Issue by fabiencomte** [Jason2866/platform-espressif32#18]
Hello,
If I try to use SerialBluetooth with an esp32-s3-devkitc-1 I got this.

c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL8_stop_btv+0x18): undefined reference to `esp_spp_disconnect'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL8_stop_btv+0x1c): undefined reference to `esp_spp_deinit'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL16_spp_send_bufferv+0xc): undefined reference to `esp_spp_write'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL8btSetPinv+0xc): undefined reference to `esp_bt_gap_set_pin'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZN15BluetoothSerial5beginE6Stringb+0x34): undefined reference to `esp_bt_gap_register_callback'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZN15BluetoothSerial5beginE6Stringb+0x38): undefined reference to `esp_spp_register_callback'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZN15BluetoothSerial5beginE6Stringb+0x3c): undefined reference to `esp_spp_init'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZN15BluetoothSerial5beginE6Stringb+0x40): undefined reference to `esp_bt_gap_set_security_param'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZN15BluetoothSerial5beginE6Stringb+0x44): undefined reference to `esp_bt_gap_set_cod'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL10esp_spp_cb18esp_spp_cb_event_tP18esp_spp_cb_param_t+0x28): undefined reference to `esp_bt_gap_set_scan_mode'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL10esp_spp_cb18esp_spp_cb_event_tP18esp_spp_cb_param_t+0x2c): undefined reference to `esp_spp_start_srv'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL10esp_spp_cb18esp_spp_cb_event_tP18esp_spp_cb_param_t+0x30): undefined reference to `esp_spp_connect'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL13esp_bt_gap_cb21esp_bt_gap_cb_event_tP21esp_bt_gap_cb_param_t+0x20): undefined reference to `esp_bt_gap_resolve_eir_data'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL13esp_bt_gap_cb21esp_bt_gap_cb_event_tP21esp_bt_gap_cb_param_t+0x28): undefined reference to `esp_bt_gap_cancel_discovery'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL13esp_bt_gap_cb21esp_bt_gap_cb_event_tP21esp_bt_gap_cb_param_t+0x2c): undefined reference to `esp_spp_start_discovery'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL13esp_bt_gap_cb21esp_bt_gap_cb_event_tP21esp_bt_gap_cb_param_t+0x34): undefined reference to `esp_bt_gap_pin_reply'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o):(.literal._ZL13esp_bt_gap_cb21esp_bt_gap_cb_event_tP21esp_bt_gap_cb_param_t+0x38): undefined reference to `esp_bt_gap_ssp_confirm_reply'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `_stop_bt()':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:716: undefined reference to `esp_spp_disconnect'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:717: undefined reference to `esp_spp_deinit'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `_spp_send_buffer()':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:189: undefined reference to `esp_spp_write'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `btSetPin()':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:153: undefined reference to `esp_bt_gap_set_pin'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `BluetoothSerial::begin(String, bool)':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:651: undefined reference to `esp_bt_gap_register_callback'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `_init_bt':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:666: undefined reference to `esp_spp_register_callback'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:666: undefined reference to `esp_spp_init'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:693: undefined reference to `esp_bt_gap_set_security_param'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:697: undefined reference to `esp_bt_gap_set_cod'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `esp_spp_cb(esp_spp_cb_event_t, esp_spp_cb_param_t*)':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:265: undefined reference to `esp_bt_gap_set_scan_mode'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:271: undefined reference to `esp_spp_start_srv'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:284: undefined reference to `esp_spp_disconnect'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:364: undefined reference to `esp_spp_connect'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:393: undefined reference to `esp_spp_disconnect'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `esp_bt_gap_cb(esp_bt_gap_cb_event_t, esp_bt_gap_cb_param_t*)':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:128: undefined reference to `esp_bt_gap_resolve_eir_data'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `get_name_from_eir':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:129: undefined reference to `esp_bt_gap_resolve_eir_data'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/esp32app/libc61/libBluetoothSerial.a(BluetoothSerial.cpp.o): in function `esp_bt_gap_cb(esp_bt_gap_cb_event_t, esp_bt_gap_cb_param_t*)':
C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:456: undefined reference to `esp_bt_gap_cancel_discovery'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:457: undefined reference to `esp_spp_start_discovery'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:530: undefined reference to `esp_bt_gap_pin_reply'
c:/users/comte/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:/Users/comte/.platformio/packages/framework-arduinoespressif32-src-def32c457c76b4d574c70dfd8f6f1217/libraries/BluetoothSerial/src/BluetoothSerial.cpp:547: undefined reference to `esp_bt_gap_ssp_confirm_reply'

**Comment by Jason2866** [comment]
S3 has no BT. So there is no serial BT
