### ISSUE TITLE
File system not available for esp32 c2

### ISSUE THREAD

**Issue by HalfSweet** [Jason2866/platform-espressif32#51]
I can't mount any filesystem on esp32 c2.

For example I am using SPIFFS and when I call `SPIFFS.begin()` to mount, this triggers an error
```
[ 921][E][SPIFFS.cpp:89] begin(): Mounting SPIFFS failed! Error: 261␍␊
```

My code is very simple

```cpp
#include <SPIFFS.h>

void setup()
{

  Serial.begin(115200);
  Serial.println("Hello");
  delay(100);
  SPIFFS.begin();
}
```

**Comment by Jason2866** [comment]
As designed. Deprecated SPIFFS is removed in our fork. For Arduino we now support **only** LittleFS

**Comment by HalfSweet** [comment]
Of course, LittleFS triggers a similar error, which appears to be a file system mount failure.

I created a new partition table and I'm not sure if this is a problem or not

```csv
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,     app,  ota_0,   0x10000, 0x100000,
app1,     app,  ota_1,   0x110000, 0x100000,
spiffs,   data, spiffs,  0x210000,0x7D000,
```

**Comment by Jason2866** [comment]
No problem with using LittleFS and the C2. You can [install Tasmota](https://jason2866.github.io/Tasmota-specials/) on the C2 and see it working ;-)
This one is verified working
```
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,     app,  ota_0,   0x10000, 0x1D0000,
app1,     app,  ota_1,   0x1E0000, 0x1D0000,
spiffs,   data, spiffs,  0x3B0000,0x50000,
```
