### ISSUE TITLE
`WiFiClientSecure` library is not included in the Arduino framework package

### ISSUE THREAD

**Issue by vshymanskyy** [Jason2866/platform-espressif32#57]
Some other libraries may also be missing, @Jason2866 is it intentional?

**Comment by Jason2866** [comment]
Yes, it is. The platfrom is designed for Tasmota use.

**Comment by playmiel** [comment]
is it not possible to include the various libraries yourself, or do you know of a fork with idf 5.0 and adruino that includes all the arduino libraries?

**Comment by Jason2866** [comment]
I removed it because we don't want it, to be there. You can give this PR a try https://github.com/platformio/platform-espressif32/pull/1281
