### ISSUE TITLE
Cannot build Zigbee examples due to missing zigbee and zboss libs

### ISSUE THREAD

**Issue by squix78** [Jason2866/platform-espressif32#66]
First of all: thank you for providing options to work with platformio and the arduino alpha release.
I'm trying to compile the zigbee examples from arduino-esp32: https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Zigbee/Zigbee_Light_Bulb 
but the zigbee and zboss libraries are missing. I tried to get around the problems by adding the libraries manually but I always end up with linker problems due to a undefined reference to a VFS function

If I'm not mistaken, this commit in the espressif arduino lib builder is missing in he 
https://github.com/Jason2866/esp32-arduino-lib-builder repository: 
https://github.com/espressif/esp32-arduino-lib-builder/commit/d48715c8b8fdb5693239b4c9876d5be12985f69e

I would do a PR for the Jason2866/esp32-arduino-lib-builder but I'm not sure if I should cherry pick the original change or just add it as regular change (also cherry picking would probably get me out of my comfort zone;-))

**Comment by Jason2866** [comment]
As designed. Everything we don't use or need for Tasmota and needs resources is removed.
