### ISSUE TITLE
HTTPClientLight

### ISSUE THREAD

**Issue by Avenitos** [Jason2866/platform-espressif32#69]
Greetings! Thank you for a good build for Platformio, I have been using it for a couple of years.

After the last update, I encountered the absence of a client for HTTPS.

As far as I understand correctly, it is supposed to use HTTPClientLight, everything works with http resources, and with https the error is -1256.

Tell me where to dig? Maybe some compilation flag forgot to specify?

**Comment by Jason2866** [comment]
As designed. It is removed, we use our own https implementation.

**Comment by Avenitos** [comment]
So I wrote this, and asked why your implementation gives such an error code :)

**Comment by Jason2866** [comment]
There is no http client included in the framework which can establish secured connections.
The client we use in Tasmota is written in Berry.
