### ISSUE TITLE
Missing components (wifi_provisioning, spiffs, mqtt)

### ISSUE THREAD

**Issue by monte-monte** [Jason2866/platform-espressif32#70]
Someone mentioned this repo for using with esp-idf and arduino as a component. But when I try to use it as a custom platform in platformio it can't resolve multiple components that are mentioned in https://github.com/espressif/arduino-esp32/blob/master/CMakeLists.txt
I've checked the actual ESP-IDF 5.1.4 and they are present, official platformio espressif32 platform also has them. 

Just manually copied those components as a workaround.

**Comment by Jason2866** [comment]
As designed and wanted.
