### ISSUE TITLE
BLE support

### ISSUE THREAD

**Issue by Brandon-Ballard25** [Jason2866/platform-espressif32#75]
Hello, I'm using the esp32-h2-devkitm-1 and I'm trying to use the 'ESP32 BLE Arduino' library but the inclusion of it causes errors i was just wondering if this library:

1. Supports Bluetooth using the 'ESP32 BLE Arduino' library 
2. If it doesn't support Bluetooth using the above library is Bluetooth supported in general?

main.cpp
```
#include <BLEDevice.h>  //error -- cannot open source file "esp_gap_ble_api.h" (dependency of "BLEDevice.h")C/C++(1696)
#include <BLEUtils.h>   //error
#include <BLEScan.h>    //error
```

platformi.int
```
[env:esp32-h2-devkitm-1]
platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF5
framework = arduino 
board = esp32-h2-devkitm-1
lib_deps = 
        ESP32 BLE Arduino
```

Thank you in advance.

**Comment by Jason2866** [comment]
This fork does not include any BLE lib.
Look here https://github.com/pioarduino/platform-espressif32
