### ISSUE TITLE
WifiSecure

### ISSUE THREAD

**Issue by Ifousoft** [Jason2866/platform-espressif32#99]
Thanks for this libs that helps me to have esp32s3 working with 7 inches display and Wifi on pio.
What about WifiSecure that I can't find there ?

Thanks!

**Comment by Jason2866** [comment]
It is removed.

**Comment by Jason2866** [comment]
A full compatible version is here https://github.com/pioarduino/platform-espressif32

**Comment by Ifousoft** [comment]
Thanks. Nevertheless I have a problem with my 7 inches screen on ESP32S3.
With the platform propose by the seller, using Wifi create a scroll on the screen each few seconds...
Using the version your provided in the fork solves this problem.

But, with the new version you propose, I got the WiFisecure... but it restarts to scroll...

Damned!

**Comment by Jason2866** [comment]
Probably the change sdkconfig how I compile the S3 OPI PSRAM Arduino variants libs
https://github.com/Jason2866/esp32-arduino-lib-builder/blob/v5.3_Arduino/configs/defconfig.opi_ram

**Comment by Ifousoft** [comment]
OK... But could you please document a little more ? I don't know what to do with your comment...
Thanks!

**Comment by Jason2866** [comment]
The changes affects the Arduino libs compile. The settings optimize performance for use with Displays

**Comment by Ifousoft** [comment]
But, How could I use this information to solve my issue on the fact that the display is scrolling... alone... :-(

**Comment by Jason2866** [comment]
Compiling the Arduino libs with this changed settings.

**Comment by Ifousoft** [comment]
Could you explain me how to recompile arduino libs ? I have no access to sdkconfig because using platformio under arduino framework.
I found in blogs that pio -t menuconfig works only fr esp-idf framework and not Arduino one.
Morevover I identified that " If you are using Arduino as the framework, it probably won't work. Arduino comes with a precompiled sdkconfig file. You can try making sure you have selected to use the esp-idf framework."...

Sorry...

**Comment by Ifousoft** [comment]
Could it be possible that you recompile a specific arduino framework with the requested config and put on github rather than 
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip

? Thanks!
